# Generated by Django 6.0.3 on 2026-03-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Kirim miqdori')),
                ('remaining_quantity', models.PositiveIntegerField(verbose_name='Qolgan miqdor')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_lot', to='production.batch')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
