# Generated by Django 6.0.3 on 2026-03-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouselot',
            name='shipped_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name="Jo'natilgan miqdor"),
        ),
        migrations.AlterField(
            model_name='warehouselot',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Qabul qilingan miqdor'),
        ),
        migrations.AlterField(
            model_name='warehouselot',
            name='remaining_quantity',
            field=models.PositiveIntegerField(verbose_name='Qoldiq'),
        ),
    ]
