# Generated by Django 6.0.3 on 2026-03-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='batch',
            name='stage',
            field=models.CharField(choices=[('QABUL', 'Qabul'), ('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyuvchi'), ('APPARAT', 'Apparatchi'), ('PALIROFKA', 'Palirofkachi'), ('SARTIROVKA', 'Sartirofkachi'), ('QAVAT', 'Qavat'), ('LAZER', 'Lazer'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], default='QABUL', max_length=30),
        ),
        migrations.AlterField(
            model_name='stagelog',
            name='from_stage',
            field=models.CharField(blank=True, choices=[('QABUL', 'Qabul'), ('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyuvchi'), ('APPARAT', 'Apparatchi'), ('PALIROFKA', 'Palirofkachi'), ('SARTIROVKA', 'Sartirofkachi'), ('QAVAT', 'Qavat'), ('LAZER', 'Lazer'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], max_length=30),
        ),
        migrations.AlterField(
            model_name='stagelog',
            name='to_stage',
            field=models.CharField(choices=[('QABUL', 'Qabul'), ('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyuvchi'), ('APPARAT', 'Apparatchi'), ('PALIROFKA', 'Palirofkachi'), ('SARTIROVKA', 'Sartirofkachi'), ('QAVAT', 'Qavat'), ('LAZER', 'Lazer'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], max_length=30),
        ),
    ]
