# Generated by Django 6.0.3 on 2026-03-15 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_batch_finished_at_remove_batch_started_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Apparat kodi')),
                ('status', models.CharField(choices=[('IDLE', "Bo'sh"), ('RUNNING', 'Ishlayapti'), ('PAUSED', 'Pauzada'), ('BROKEN', 'Buzilgan')], default='IDLE', max_length=20, verbose_name='Holati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Apparat',
                'verbose_name_plural': 'Apparatlar',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='batch',
            name='stage',
            field=models.CharField(choices=[('QABUL', 'Qabul'), ('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyish'), ('APPARAT', 'Apparat'), ('PALIROFKA', 'Palirofka'), ('SARTIROVKA', 'Sartirovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], default='QABUL', max_length=30),
        ),
        migrations.AlterField(
            model_name='stagelog',
            name='from_stage',
            field=models.CharField(blank=True, choices=[('QABUL', 'Qabul'), ('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyish'), ('APPARAT', 'Apparat'), ('PALIROFKA', 'Palirofka'), ('SARTIROVKA', 'Sartirovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], max_length=30),
        ),
        migrations.AlterField(
            model_name='stagelog',
            name='to_stage',
            field=models.CharField(choices=[('QABUL', 'Qabul'), ('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyish'), ('APPARAT', 'Apparat'), ('PALIROFKA', 'Palirofka'), ('SARTIROVKA', 'Sartirovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], max_length=30),
        ),
        migrations.CreateModel(
            name='MachineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='production.batch')),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_machine_assignments', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='production.machine')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_machine_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apparat biriktirish',
                'verbose_name_plural': 'Apparat biriktirishlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MachineBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Xabar berilgan'), ('ACCEPTED', 'Qabul qilingan'), ('FIXED', 'Tuzatildi')], default='REPORTED', max_length=20)),
                ('reason', models.TextField(blank=True, verbose_name='Buzilish sababi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_breakdowns', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='production.batch')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_breakdowns', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='production.machine')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_breakdowns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buzilish',
                'verbose_name_plural': 'Buzilishlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('QABUL', 'Qabul'), ('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyish'), ('APPARAT', 'Apparat'), ('PALIROFKA', 'Palirofka'), ('SARTIROVKA', 'Sartirovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], max_length=30)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_stage_progresses', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='production.batch')),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_stage_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('batch', 'stage')},
            },
        ),
    ]
