# Generated by Django 6.0.3 on 2026-03-15 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_machine_alter_batch_stage_alter_stagelog_from_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['department', 'code']},
        ),
        migrations.AlterModelOptions(
            name='machineassignment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='machinebreakdown',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='inspection_note',
            field=models.TextField(blank=True, verbose_name='Rang nazorati'),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_repeat',
            field=models.BooleanField(default=False, verbose_name='Takror batch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='note',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='batch',
            name='scrap_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Brak soni'),
        ),
        migrations.AddField(
            model_name='batch',
            name='source_stage',
            field=models.CharField(choices=[('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyish'), ('APPARAT', 'Apparat'), ('PALIROFKA', 'Palirofka'), ('SARTIROVKA', 'Sartirovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], default='0', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='unit_type',
            field=models.CharField(choices=[('LIST', 'List'), ('BUTTON', 'Tugma')], default='LIST', max_length=10),
        ),
        migrations.AddField(
            model_name='machine',
            name='department',
            field=models.CharField(choices=[('APPARAT', 'Apparat'), ('PALIROFKA', 'Palirofka')], default='APPARAT', max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='stage',
            field=models.CharField(choices=[('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyish'), ('APPARAT', 'Apparat'), ('PALIROFKA', 'Palirofka'), ('SARTIROVKA', 'Sartirovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], max_length=30),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('IN_PROGRESS', 'Jarayonda'), ('PAUSED', 'Pauzada'), ('HOLD', "To'xtatilgan"), ('WAREHOUSE', 'Omborda'), ('SHIPPED', "Jo'natilgan"), ('DONE', 'Tugagan')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('IDLE', "Bo'sh"), ('RUNNING', 'Ishlayapti'), ('PAUSED', 'Pauzada'), ('BROKEN', 'Buzilgan')], default='IDLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='machinebreakdown',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='machinebreakdown',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stagelog',
            name='from_stage',
            field=models.CharField(blank=True, choices=[('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyish'), ('APPARAT', 'Apparat'), ('PALIROFKA', 'Palirofka'), ('SARTIROVKA', 'Sartirovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], max_length=30),
        ),
        migrations.AlterField(
            model_name='stagelog',
            name='to_stage',
            field=models.CharField(choices=[('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyish'), ('APPARAT', 'Apparat'), ('PALIROFKA', 'Palirofka'), ('SARTIROVKA', 'Sartirovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], max_length=30),
        ),
        migrations.AlterField(
            model_name='stageprogress',
            name='stage',
            field=models.CharField(choices=[('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyish'), ('APPARAT', 'Apparat'), ('PALIROFKA', 'Palirofka'), ('SARTIROVKA', 'Sartirovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], max_length=30),
        ),
    ]
