# Generated by Django 6.0.3 on 2026-03-16 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_orderitem_options_and_more'),
        ('production', '0004_alter_batch_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='capacity',
            field=models.PositiveIntegerField(default=1, verbose_name="Sig'imi"),
        ),
        migrations.AddField(
            model_name='machineassignment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='machinebreakdown',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='machineassignment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='production.batch'),
        ),
        migrations.AlterField(
            model_name='machinebreakdown',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='production.batch'),
        ),
    ]
