# Generated by Django 6.0.3 on 2026-03-16 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_machine_capacity_machineassignment_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='machineassignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='machinebreakdown',
            name='order',
        ),
        migrations.AlterField(
            model_name='machineassignment',
            name='batch',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='production.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machinebreakdown',
            name='batch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='production.batch'),
            preserve_default=False,
        ),
    ]
