# Generated by Django 6.0.2 on 2026-03-05 00:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Batch', max_length=50, verbose_name='Batch nomi')),
                ('kg_plan', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Batch kg (reja)')),
                ('list_plan', models.PositiveIntegerField(default=0, verbose_name='Batch list (reja)')),
                ('kg_done', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tayyor kg')),
                ('list_done', models.PositiveIntegerField(default=0, verbose_name='Tayyor list')),
                ('stage', models.CharField(choices=[('QABUL', 'Zakaz qabul'), ('RANG', 'Rang tayyor'), ('QUYISH', 'Quyish'), ('APARAT', 'Aparat'), ('YUVISH', 'Yuvish'), ('MATIVIY', 'Mativiy'), ('SARTAROFKA', 'Sartarofka'), ('UPAKOVKA', 'Upakovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish"), ('DONE', 'Yakunlandi')], default='QABUL', max_length=20, verbose_name='Bosqich')),
                ('is_done', models.BooleanField(default=False, verbose_name='Tugadi')),
                ('is_paused', models.BooleanField(default=False, verbose_name="To'xtatilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batchlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Rang nomi')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Joy (location)')),
            ],
            options={
                'verbose_name': 'Joy',
                'verbose_name_plural': 'Joylar',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, default='', max_length=200, verbose_name="Kimga jo'natildi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Jo'natish",
                'verbose_name_plural': "Jo'natishlar",
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Yuvish kodi')),
            ],
            options={
                'verbose_name': 'Yuvish apparati',
                'verbose_name_plural': 'Yuvish apparatlari',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Aparat kodi')),
                ('status', models.CharField(choices=[('IDLE', "Bo'sh"), ('BUSY', 'Band'), ('BROKEN', 'Buzilgan'), ('MAINT', "Ta'mirda")], default='IDLE', max_length=20, verbose_name='Holati')),
                ('busy_since', models.DateTimeField(blank=True, null=True, verbose_name="Band bo'lgan vaqti")),
                ('current_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_on', to='main.batch', verbose_name='Hozirgi batch')),
            ],
            options={
                'verbose_name': 'Aparat',
                'verbose_name_plural': 'Aparatlar',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.machine', verbose_name='Aparat'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Zakaz beruvchi nomi')),
                ('size_mm', models.PositiveIntegerField(verbose_name="O'lcham (mm)")),
                ('kg_plan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nechi kg quyish')),
                ('list_plan', models.PositiveIntegerField(default=0, verbose_name='List soni')),
                ('finish', models.CharField(choices=[('YALTIROQ', 'Yaltiroq'), ('MATIVIY', 'Mativiy')], default='YALTIROQ', max_length=20, verbose_name='Finish')),
                ('laser', models.BooleanField(default=False, verbose_name='Lazer')),
                ('laser_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Lazer matni')),
                ('stage', models.CharField(choices=[('QABUL', 'Zakaz qabul'), ('RANG', 'Rang tayyor'), ('QUYISH', 'Quyish'), ('APARAT', 'Aparat'), ('YUVISH', 'Yuvish'), ('MATIVIY', 'Mativiy'), ('SARTAROFKA', 'Sartarofka'), ('UPAKOVKA', 'Upakovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish"), ('DONE', 'Yakunlandi')], default='QABUL', max_length=20, verbose_name='Bosqich')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.color', verbose_name='Rang')),
            ],
            options={
                'verbose_name': 'Zakaz',
                'verbose_name_plural': 'Zakazlar',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='main.order', verbose_name='Zakaz'),
        ),
        migrations.CreateModel(
            name='PackingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs', models.PositiveIntegerField(default=0, verbose_name='Pachka')),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg')),
                ('pcs', models.PositiveIntegerField(default=0, verbose_name='Dona')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_lots', to='main.order', verbose_name='Zakaz')),
            ],
            options={
                'verbose_name': 'Upakovka lot',
                'verbose_name_plural': 'Upakovka lotlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, default='', max_length=20)),
                ('to_stage', models.CharField(choices=[('QABUL', 'Zakaz qabul'), ('RANG', 'Rang tayyor'), ('QUYISH', 'Quyish'), ('APARAT', 'Aparat'), ('YUVISH', 'Yuvish'), ('MATIVIY', 'Mativiy'), ('SARTAROFKA', 'Sartarofka'), ('UPAKOVKA', 'Upakovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish"), ('DONE', 'Yakunlandi')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='main.batch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.order')),
            ],
            options={
                'verbose_name': 'Bosqich log',
                'verbose_name_plural': 'Bosqich loglar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('IN_PROGRESS', 'Jarayonda'), ('DONE', 'Yopildi')], default='OPEN', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rtacha"), ('HIGH', 'Yuqori')], default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Muammo nomi')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tickets/', verbose_name='Foto')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='main.machine')),
            ],
            options={
                'verbose_name': 'Nosozlik ticket',
                'verbose_name_plural': 'Nosozlik ticketlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=30, unique=True, verbose_name='Lot kodi')),
                ('packs_total', models.PositiveIntegerField(default=0)),
                ('pcs_total', models.PositiveIntegerField(default=0)),
                ('kg_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('packs_left', models.PositiveIntegerField(default=0)),
                ('pcs_left', models.PositiveIntegerField(default=0)),
                ('kg_left', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location')),
                ('packing_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_lots', to='main.packinglot')),
            ],
            options={
                'verbose_name': 'Ombor lot',
                'verbose_name_plural': 'Ombor lotlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs', models.PositiveIntegerField(default=0)),
                ('pcs', models.PositiveIntegerField(default=0)),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.shipment')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.warehouselot')),
            ],
            options={
                'verbose_name': "Jo'natish item",
                'verbose_name_plural': "Jo'natish itemlar",
            },
        ),
        migrations.CreateModel(
            name='WashingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshladi')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugadi')),
                ('is_done', models.BooleanField(default=False, verbose_name='Yakunlandi')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.washingmachine', verbose_name='Yuvish apparati')),
            ],
            options={
                'verbose_name': 'Yuvish load',
                'verbose_name_plural': 'Yuvish loadlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WashingLoadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.batch')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.washingload')),
            ],
            options={
                'verbose_name': 'Load item',
                'verbose_name_plural': 'Load itemlar',
                'unique_together': {('load', 'batch')},
            },
        ),
    ]
