# Generated by Django 6.0.3 on 2026-03-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='coating',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='kg_per_sheet',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coating_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Qavat izohi'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_coated',
            field=models.BooleanField(default=False, verbose_name='Qavatli'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='laser_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lazer yozuvi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='smala_kg',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Smala kg'),
        ),
    ]
