# Generated by Django 6.0.3 on 2026-03-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='order',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ishlab chiqarishga o'tkazilgan vaqt"),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Saqlangan'), ('RELEASED', "Ishlab chiqarishga o'tkazilgan")], default='DRAFT', max_length=20, verbose_name='Holati'),
        ),
    ]
