# Generated by Django 6.0.3 on 2026-03-08 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='Batch list soni')),
                ('stage', models.CharField(choices=[('QABUL', 'Qabul'), ('QUYISH', 'Quyish'), ('APARAT', 'Aparat'), ('QAVAT', 'Qavat'), ('MATEVIY', 'Mateviy'), ('LAZER', 'Lazer'), ('YUVISH', 'Yuvish'), ('UPAKOVKA', 'Upakovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], default='QABUL', max_length=30)),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('IN_PROGRESS', 'Jarayonda'), ('DONE', 'Tayyor'), ('WAREHOUSE', 'Omborda'), ('SHIPPED', "Jo'natilgan"), ('HOLD', "To'xtatilgan")], default='NEW', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='orders.orderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, choices=[('QABUL', 'Qabul'), ('QUYISH', 'Quyish'), ('APARAT', 'Aparat'), ('QAVAT', 'Qavat'), ('MATEVIY', 'Mateviy'), ('LAZER', 'Lazer'), ('YUVISH', 'Yuvish'), ('UPAKOVKA', 'Upakovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], max_length=30)),
                ('to_stage', models.CharField(choices=[('QABUL', 'Qabul'), ('QUYISH', 'Quyish'), ('APARAT', 'Aparat'), ('QAVAT', 'Qavat'), ('MATEVIY', 'Mateviy'), ('LAZER', 'Lazer'), ('YUVISH', 'Yuvish'), ('UPAKOVKA', 'Upakovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='production.batch')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
