# Generated by Django 6.0.3 on 2026-03-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='Zakas raqami')),
                ('accepted_at', models.DateField(verbose_name='Qabul qilingan sana')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Firma nomi')),
                ('due_at', models.DateTimeField(verbose_name='Topshirish vaqti')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('CONFIRMED', 'Tasdiqlangan'), ('IN_PROGRESS', 'Ishlab chiqarishda'), ('PARTIAL_READY', 'Qisman tayyor'), ('READY', 'Tayyor'), ('SHIPPED', "Jo'natilgan"), ('CANCELLED', 'Bekor qilingan')], default='NEW', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zakas',
                'verbose_name_plural': 'Zakazlar',
                'ordering': ['-accepted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Razmer')),
                ('color', models.CharField(max_length=100, verbose_name='Rangi')),
                ('coating', models.CharField(choices=[('SADAF', 'Sadaf'), ('POLEGAL', 'Polegal'), ('NONE', 'Qavatsiz')], default='NONE', max_length=20, verbose_name='Sadaf yoki polegal')),
                ('techik_count', models.PositiveIntegerField(default=0, verbose_name='Techik soni')),
                ('surface', models.CharField(choices=[('MATTE', 'Mateviy'), ('GLOSSY', 'Yaltiroq')], max_length=20, verbose_name='Mateviy yoki yaltiroq')),
                ('laser', models.CharField(choices=[('LASER', 'Lazerli'), ('NO_LASER', 'Lazersiz')], default='NO_LASER', max_length=20, verbose_name='Lazer yoki lazersiz')),
                ('sheet_count', models.PositiveIntegerField(verbose_name='List soni')),
                ('button_count', models.PositiveIntegerField(default=0, verbose_name='Tugma soni')),
                ('kg_per_sheet', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='1 listga ketadigan kg')),
                ('smala_kg', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='Smala kg')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Zakas')),
            ],
            options={
                'verbose_name': 'Zakas qatori',
                'verbose_name_plural': 'Zakas qatorlari',
                'ordering': ['id'],
            },
        ),
    ]
