# Generated by Django 6.0.3 on 2026-03-15 13:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_options_order_released_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': 'Zakaz tarkibi', 'verbose_name_plural': 'Zakaz tarkiblari'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='techik_count',
        ),
        migrations.AddField(
            model_name='order',
            name='current_stage',
            field=models.CharField(choices=[('RANG_TAYYORLASH', 'Rang tayyorlash'), ('QUYISH', 'Quyish'), ('APPARAT', 'Apparat'), ('PALIROFKA', 'Palirofka'), ('SARTIROVKA', 'Sartirovka'), ('OMBOR', 'Ombor'), ('JONATISH', "Jo'natish")], default='RANG_TAYYORLASH', max_length=30, verbose_name="Joriy bo'lim"),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2026, 3, 15), verbose_name='Sana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='use_order_flow',
            field=models.BooleanField(default=True, verbose_name="Zakaz o'zi worker oqimida ko'rinsin"),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Qavat soni'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='hole_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Teshigi soni'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='material_type',
            field=models.CharField(choices=[('SADAF', 'Sadaf'), ('POLEGAL', 'Polegal')], default='SADAF', max_length=20, verbose_name='Sadaf / Polegal'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pantone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pantone'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='primary_color',
            field=models.CharField(default='', max_length=100, verbose_name='Asosiy rangi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qavat rangi'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='thickness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Qalinligi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(max_length=30, unique=True, verbose_name='Zakaz raqami'),
        ),
        migrations.AlterField(
            model_name='order',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Jarayonga o'tgan vaqt"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('RELEASED', 'Ish jarayonida'), ('DONE', 'Tugadi')], default='DRAFT', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='button_count',
            field=models.PositiveIntegerField(verbose_name='Umumiy tugma soni'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='laser',
            field=models.CharField(choices=[('LASER', 'Lazer'), ('NO_LASER', 'Lazersiz')], default='NO_LASER', max_length=20, verbose_name='Lazer / Lazersiz'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Zakaz'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Razmeri'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='surface',
            field=models.CharField(choices=[('MATTE', 'Mat'), ('GLOSSY', 'Yalt')], max_length=20, verbose_name='Mat / Yalt'),
        ),
    ]
